name: Build Windows AMD64

on:
  release:
    types: [published]

env:
    ASSET_NAME: "taz-windows_arm64.zip"
    ASSET_FILES: "taz.exe"

jobs:
  build:
    runs-on: windows-arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build and create archive
        run: |
            make

      - name: Rename binary to .exe
        run: |
          if (Test-Path .\taz) { Move-Item -Path .\taz -Destination .\taz.exe }

      - name: Compress artifact
        run: Compress-Archive -Path ${{ env.ASSET_FILES }} -DestinationPath ${{ env.ASSET_NAME }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/octet-stream
